apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecommerce-monitor
  labels:
    app: ecommerce
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ecommerce
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
