apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ecommerce-alerts
  labels:
    app: ecommerce
    release: prometheus
spec:
  groups:
  - name: ecommerce
    interval: 30s
    rules:
    # Application availability
    - alert: EcommerceAppDown
      expr: up{job="ecommerce-service"} == 0
      for: 1m
      labels:
        severity: critical
        app: ecommerce
      annotations:
        summary: "E-commerce application is down"
        description: "E-commerce app {{ $labels.instance }} has been down for more than 1 minute"
    
    # High error rate
    - alert: HighErrorRate
      expr: rate(flask_http_request_total{status=~"5.."}[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
        app: ecommerce
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }} errors per second on {{ $labels.instance }}"
    
    # High response time
    - alert: HighResponseTime
      expr: flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count > 1
      for: 3m
      labels:
        severity: warning
        app: ecommerce
      annotations:
        summary: "High response time detected"
        description: "Average response time is {{ $value }}s on {{ $labels.instance }}"
    
    # High memory usage
    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"ecommerce-app-.*"} / container_spec_memory_limit_bytes{pod=~"ecommerce-app-.*"} > 0.85
      for: 5m
      labels:
        severity: warning
        app: ecommerce
      annotations:
        summary: "High memory usage"
        description: "Memory usage is {{ $value | humanizePercentage }} on pod {{ $labels.pod }}"
    
    # High CPU usage
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"ecommerce-app-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        app: ecommerce
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is {{ $value | humanizePercentage }} on pod {{ $labels.pod }}"
    
    # Pod restart
    - alert: PodRestarting
      expr: rate(kube_pod_container_status_restarts_total{pod=~"ecommerce-app-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: warning
        app: ecommerce
      annotations:
        summary: "Pod is restarting frequently"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"
    
    # Low request rate (potential issue)
    - alert: LowRequestRate
      expr: rate(flask_http_request_total[5m]) < 0.01
      for: 10m
      labels:
        severity: info
        app: ecommerce
      annotations:
        summary: "Low request rate detected"
        description: "Request rate is very low: {{ $value }} requests/sec on {{ $labels.instance }}"
